package com.github.grishberg.openscad.utils

enum class Side {
    TOP, TOP_IN, TOP_OUT, TOP_IN_CENTER, TOP_OUT_CENTER,
    BOTTOM, BOTTOM_IN, BOTTOM_OUT, BOTTOM_IN_CENTER, BOTTOM_OUT_CENTER,
    LEFT, LEFT_IN, LEFT_OUT, LEFT_IN_CENTER, LEFT_OUT_CENTER,
    RIGHT, RIGHT_IN, RIGHT_OUT, RIGHT_IN_CENTER, RIGHT_OUT_CENTER,
    FRONT, FRONT_IN, FRONT_OUT, FRONT_IN_CENTER, FRONT_OUT_CENTER,
    BACK, BACK_IN, BACK_OUT, BACK_IN_CENTER, BACK_OUT_CENTER,
    CENTER, OUT, IN
}
